// Usage: NODE_PATH=/path/to/node_modules BROWSER_EXECUTABLE=/path/to/chromium node scripts/browser-smoke.cjs
// Starts a loopback server and never submits an enquiry to an external recipient.
const {chromium}=require('playwright');
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(process.argv[2]||'_site');
const server=http.createServer((req,res)=>{const u=new URL(req.url,'http://localhost');const file=path.resolve(root,'.'+decodeURIComponent(u.pathname)+(u.pathname.endsWith('/')?'index.html':''));if(!file.startsWith(root+path.sep)){res.writeHead(403);return res.end();}try{const b=fs.readFileSync(file);res.setHeader('Content-Type',({'.html':'text/html; charset=utf-8','.css':'text/css','.js':'application/javascript','.svg':'image/svg+xml','.png':'image/png','.webp':'image/webp','.webmanifest':'application/manifest+json'})[path.extname(file)]||'text/plain');res.end(b);}catch{res.writeHead(404);res.end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;const browser=await chromium.launch({executablePath:process.env.BROWSER_EXECUTABLE||undefined,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu'],headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[],missing=[],outbound=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)missing.push(r.url());});await page.route('**/*',route=>{if(route.request().url().startsWith(origin))return route.continue();outbound.push(route.request().url());return route.abort();});
try{
 for(const width of [1440,768,390,320]){await page.setViewportSize({width,height:900});for(const url of ['/','/uslugi/','/uslugi/semeynaya-ipoteka/','/online-zayavka/','/kalkulyator-ipoteki/','/kontakty/']){await page.goto(origin+url);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,'horizontal overflow '+width+' '+url);}console.log('Responsive routes OK:',width);}
 await page.goto(origin+'/');await page.locator('.nav-toggle').click();assert.equal(await page.locator('.nav-toggle').getAttribute('aria-expanded'),'true');await page.keyboard.press('Escape');assert.equal(await page.locator('.nav-toggle').getAttribute('aria-expanded'),'false');
 const screenshotDir=process.env.SCREENSHOT_DIR;if(screenshotDir){fs.mkdirSync(screenshotDir,{recursive:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(screenshotDir,'mobile.png'),fullPage:true});await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:path.join(screenshotDir,'desktop.png'),fullPage:true});}
 await page.goto(origin+'/online-zayavka/');await page.waitForSelector('form[data-application-ready="true"]');await page.locator('[data-application-submit]').click();assert.equal(await page.locator('[data-application-result]').isVisible(),false,'empty form accepted');await page.locator('[name=client_name]').fill('Тест интерфейса');await page.locator('[name=phone]').fill('9001234567');await page.locator('[name=scenario]').selectOption({label:'Покупка дома'});await page.locator('[name=consent]').check();await page.locator('[data-application-submit]').click();assert.equal(await page.locator('[data-application-result]').isVisible(),true);const text=await page.locator('[data-application-output]').inputValue();assert.ok(text.includes('Тест интерфейса'));assert.match(await page.locator('[data-application-sms]').getAttribute('href'),/^sms:\+79626187473\?body=/);assert.equal(await page.locator('[data-application-direct-send]').isVisible(),false,'disabled backend advertised');assert.match(await page.locator('[data-application-status]').innerText(),/не отправлено/);await page.locator('[name=client_name]').fill('Изменённое имя');assert.equal(await page.locator('[data-application-result]').isVisible(),false,'stale enquiry retained');
 await page.goto(origin+'/kalkulyator-ipoteki/');await page.locator('[name=rate]').fill('0');await page.locator('[name=amount]').fill('3500000');await page.locator('[name=down]').fill('500000');await page.locator('[name=years]').fill('20');await page.locator('[name=years]').blur();assert.match(await page.locator('[data-calc-result]').innerText(),/12\s?500/);console.log('Form validation, SMS handoff, stale data and calculator OK');assert.deepEqual(errors,[]);assert.deepEqual(missing,[]);assert.deepEqual(outbound,[]);console.log('Browser acceptance passed: no JS errors, missing assets or external transmissions');
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
